title: OHMind Documentation
description: Documentation for the OHMind platform
remote_theme: rundocs/jekyll-rtd-theme
markdown: kramdown
permalink: pretty

# Logo
logo: /logo.png

# RTD theme settings
lang: en
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

# Navigation
header_pages:
  - index.md
  - ohmind_user_guide.md

# Footer content
footer_content: "<strong>PolyAI Team</strong><br/>Copyright &copy; 2009-2025 Changchun Institute of Applied Chemistry, Chinese Academy of Sciences<br/>Address: No. 5625, Renmin Street, Changchun, Jilin, China. Postal Code: 130022"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
